baseurl      = "/"
languageCode = "en-us"
theme        = "hello-friend-ng"
title        = "home"
paginate     = 10


defaultContentLanguage = "en"

googleAnalytics = "G-GXDRCDCX0B"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006 15:04"

  enableThemeToggle = true


  [params.logo]
    logoText     = "/"
    logoHomeLink = "/"

  [[params.social]]
    name = "email"
    url  = "iker@lissarrague.xyz"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Ikerlb/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/iker-lissarrague/"




  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]


[taxonomies]
    category = "blog"
    tag      = "tags"

[languages]
  [languages.en]
	title     = "about me"
    subtitle = "lissarrague.xyz"
    readOtherPosts = "Read other posts"

[menu]
  [[menu.main]]
    identifier = "reading_log"
    name       = "reading log"
    url        = "reading_log/"
  [[menu.main]]
    identifier = "projects"
    name       = "projects"
    url        = "projects/"
